### ISSUE TITLE
Failed to activate the script-runner package

### ISSUE THREAD

**Issue by kovtun-alex** [ioquatix/script-runner#105]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package 2.5.0

### Stack Trace

Failed to activate the script-runner package

```
At Cannot find module 'node-pty'

Error: Cannot find module 'node-pty'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/script-runner-master/lib/script-runner-process.js:3:13)
    at /packages/script-runner-master/lib/script-runner-process.js:207:38)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/script-runner/lib/script-runner.js:6:27)
    at /packages/script-runner/lib/script-runner.js:179:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3430498)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418632)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418410)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3416041)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418270)
    at new Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-color-the-tag-name 1.14.0 
atom-django 0.3.2 
atom-html-preview 0.2.6 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-python-virtualenv 1.0.3 
atom-wrap-in-tag 0.6.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
autocomplete-python 1.14.1 
awesome-python-snippets 0.3.0 
busy-signal 2.0.1 
color-indent 1.0.2 
color-picker 2.3.0 
css-snippets 1.1.0 
double-tag 1.7.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.33 
flexbox-snippets 0.3.0 
highlight-selected 0.16.0 
html-tag-auto-complete 0.1.1 
ide-php 0.7.18 
ide-python 1.4.1 
intentions 1.1.5 
language-kotlin 0.5.0 
language-swift 0.5.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-kotlin 0.6.0 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
minimap 4.29.9 
monokai 0.24.0 
pdf-view 0.71.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
python-snippets 1.9.0 
python-tools 0.6.9 
script 3.18.1 
script-runner 2.5.0 
swift-autocomplete-snippets 0.1.0 
swift-debugger 0.1.2 
```

**Comment by ioquatix** [comment]
This should be fixed by v2.6.0 can you please check?
