### ISSUE TITLE
Unable to install Script-Runner

### ISSUE THREAD

**Issue by dan96kid** [ioquatix/script-runner#107]
> node-pty@0.8.1 install C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty
> node scripts/install.js

C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\Tribus\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Tribus\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\conpty.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\conpty.vcxproj]
  
  
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\conpty_console_list.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\conpty_console_list.vcxproj]
  
  
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\deps\winpty\src\winpty.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\deps\winpty\src\winpty.vcxproj]
  
  
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  
  

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Tribus\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Tribus\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Tribus\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\node_modules\script-runner\node_modules\node-pty
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12018-6940-1m2snfl.opfq\package.json'
npm WARN apm-install-dir-12018-6940-1m2snfl.opfq No description
npm WARN apm-install-dir-12018-6940-1m2snfl.opfq No repository field.
npm WARN apm-install-dir-12018-6940-1m2snfl.opfq No README data
npm WARN apm-install-dir-12018-6940-1m2snfl.opfq No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tribus\.atom\.apm\_logs\2020-02-09T01_17_12_685Z-debug.log

**Comment by ioquatix** [comment]
Windows is not supported at this time because node-gyp is broken. It's out of scope but I wish it was fixed.
