### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getActiveItem' of null

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#17]
[Enter steps to reproduce below:]

1. Run script
2. It is still running, close script output window.
3. Try to run again.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getActiveItem' of null

```
At /Users/samuel/.atom/packages/script-runner/lib/script-runner.coffee:118

TypeError: Cannot read property 'getActiveItem' of null
  at ScriptRunner.stop (/Users/samuel/.atom/packages/script-runner/lib/script-runner.coffee:118:32)
  at atom-workspace.atom.commands.add.run:terminate (/Users/samuel/.atom/packages/script-runner/lib/script-runner.coffee:32:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/User/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/User/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/User/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/User/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/User/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -7:30.5 core:move-down (atom-text-editor.editor.is-focused)
     -7:30.2 editor:newline (atom-text-editor.editor.is-focused)
     -7:29.9 core:move-up (atom-text-editor.editor.is-focused)
     -7:29.7 editor:newline (atom-text-editor.editor.is-focused)
     -7:29.5 core:move-down (atom-text-editor.editor.is-focused)
     -7:29.3 core:paste (atom-text-editor.editor.is-focused)
     -7:28.8 core:backspace (atom-text-editor.editor.is-focused)
     -7:28.4 core:save (atom-text-editor.editor.is-focused)
  8x -7:26.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:21.5 core:move-right (atom-text-editor.editor.is-focused)
     -7:19.4 core:save (atom-text-editor.editor.is-focused)
  2x -7:14.3 core:backspace (atom-text-editor.editor.is-focused)
     -6:54.9 run:script (atom-text-editor.editor.is-focused)
  2x -0:05.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.3 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.3 run:terminate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
file-icons, v1.4.8
language-latex, v0.4.1
language-trenni, v0.2.0
latex, v0.16.0
pdf-view, v0.14.0
pretty-json, v0.3.2
script-runner, v1.7.0
svg-preview, v0.4.0
tabs-to-spaces, v0.8.1
travis-ci-status, v0.11.2
web-view, v0.3.0

# Dev
No dev packages
```

/cc @huba

**Comment by huba** [comment]
It happens when you trigger the terminate command while there are no existing runners.
SHA: 782a1ac315695afc90b6e7970b9a18b1a102ef37 hopefully should fix it

**Comment by huba** [comment]
You should probably see if the problem is gone before closing anything.

**Comment by ioquatix** [comment]
Yeah this is fixed, thanks, awesome work!
