### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by PWmercy** [ioquatix/script-runner#30]
[Enter steps to reproduce below:]

1. ...Cursor in test.php
2. ...Control-x

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v1.7.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/admin/.atom/packages/script-runner/lib/script-runner.coffee:133

TypeError: undefined is not a function
  at ScriptRunner.commandFor (/Users/admin/.atom/packages/script-runner/lib/script-runner.coffee:133:36)
  at ScriptRunner.run (/Users/admin/.atom/packages/script-runner/lib/script-runner.coffee:102:12)
  at atom-workspace.atom.commands.add.run:script (/Users/admin/.atom/packages/script-runner/lib/script-runner.coffee:31:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -7:53.7.0 core:select-all (atom-text-editor.editor)
     -7:52.1.0 run:script (atom-text-editor.editor)
 12x -7:21.2.0 core:backspace (atom-text-editor.editor)
     -7:04.1.0 core:select-all (atom-text-editor.editor)
     -7:02.7.0 run:script (atom-text-editor.editor)
     -2:36.1.0 core:select-all (atom-text-editor.editor)
     -2:33.8.0 editor:consolidate-selections (atom-text-editor.editor)
     -2:33.8.0 core:cancel (atom-text-editor.editor)
     -2:32.8.0 core:move-left (atom-text-editor.editor)
     -2:31 run:script (atom-text-editor.editor)
     -2:26.1.0 core:cancel (div.script-runner)
  2x -1:50.1.0 run:script (atom-text-editor.editor)
     -0:44.2.0 core:move-up (atom-text-editor.editor)
     -0:43.3.0 run:script (atom-text-editor.editor)
     -0:03.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.5.0 run:script (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
script-runner, v1.7.3

# Dev
No dev packages
```

**Comment by ioquatix** [comment]
Release v1.8.0 to fix this.
