### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by vshafir** [ioquatix/script-runner#36]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v1.8.3

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:374:25)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:297:14)
  at ScriptRunner.run (/Users/vlad/.atom/packages/script-runner/lib/script-runner.coffee:91:11)
  at atom-workspace.atom.commands.add.run:script (/Users/vlad/.atom/packages/script-runner/lib/script-runner.coffee:32:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:48.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:48.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:43.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:40.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:37.6.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:36.3.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
  2x -0:32.5.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -0:31.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:30.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:20.3.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:18.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  7x -0:10.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1.0 run:script (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
autocomplete-python, v0.5.1
live-doc-viewer, v1.0.6
script-runner, v1.8.3
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by ioquatix** [comment]
Was this a bug?

**Comment by vshafir** [comment]
There was some sort of exception. I’m such a newbie that I wouldn’t be able to intelligently describe it.
Let’s skip it. Thanks for your prompt response.

-Vlad.

**Comment by kenkotch** [comment]
when working with screen split in half w/ 1 .js file on left and right, trying to use script-runner on bottom right quadrant. Tries to open a third column

**Comment by ioquatix** [comment]
@kenkotch Can you please open a new issue with screenshots? I'm doing some work on the UI so would be good to discuss.
