### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by sxbrahme** [ioquatix/script-runner#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v1.8.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1119

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1119:26)
    at Object.exports.spawn (child_process.js:977:9)
    at ShellEnvironment.getLoginEnvironmentFromShell (C:\Users\sabra\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:59:28)
    at ShellEnvironment.getBestEnvironment (C:\Users\sabra\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:47:19)
    at ShellEnvironment.getEnvironment (C:\Users\sabra\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:36:14)
    at Function.ShellEnvironment.loginEnvironment (C:\Users\sabra\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:92:36)
    at ScriptRunner.run (C:\Users\sabra\.atom\packages\script-runner\lib\script-runner.coffee:156:31)
    at atom-workspace.atom.commands.add.run:script (C:\Users\sabra\.atom\packages\script-runner\lib\script-runner.coffee:58:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sabra\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
```

### Commands

```
     -1:06.2.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:02.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:02.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.5.0 run:script (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.10
emmet, v2.3.12
jshint, v1.3.9
script-runner, v1.8.3

# Dev
No dev packages
```

**Comment by ioquatix** [comment]
Windows support is broken at the moment due to lack of obvious pseudo-tty support. It's something we are working on, thanks for reporting this bug.

**Comment by huba** [comment]
@ioquatix do you think we should prevent apm installing it? Just to avoid disappointing potential users. PR #27
