### ISSUE TITLE
Failed to load the script-runner package: Cannot find module 'shellwords'

### ISSUE THREAD

**Issue by MySpeed** [ioquatix/script-runner#53]
I'm really confused about this and have been trying to install it different ways into the atom text editor but it never works. It keeps giving this error: 

Error: Cannot find module 'shellwords'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/roycben20/.atom/packages/script-runner-1.8.4/lib/script-runner-process.coffee:3:14)
    at Object.<anonymous> (file:///C:/Users/roycben20/.atom/packages/script-runner-1.8.4/lib/script-runner-process.coffee:1:1)
    at Module._compile (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:Usersroycben20AppDataLocalatomapp-1.11.2resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/roycben20/.atom/packages/script-runner-1.8.4/lib/script-runner.coffee:3:23)
    at Object.<anonymous> (file:///C:/Users/roycben20/.atom/packages/script-runner-1.8.4/lib/script-runner.coffee:1:1)
    at Module._compile (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:Usersroycben20AppDataLocalatomapp-1.11.2resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\roycben20\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:759:28

**Comment by ioquatix** [comment]
Sorry right now it seems like we have some issues on windows.

**Comment by ioquatix** [comment]
Okay, I found that if you install using the git master branch you can get this error. This happens because script-runner depends on shellwords but it's not included by default, it needs to be installed by npm/apm.

If you go into your package directory, e.g. `~/.atom/packages/script-runner` and execute `apm install` it will work. At least, I had same error, and that installed a whole bunch of stuff into `~/.atom/packages/script-runner/node_modules` including `shellwords`.

Hope that helps.
