### ISSUE TITLE
Unsaved script error.

### ISSUE THREAD

**Issue by huba** [ioquatix/script-runner#57]
1. write script
2. don't save
3. run

**Atom Version**: 1.12.6
**Electron Version**: 1.4.11
**System**: linux 4.8.12-2-ARCH
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v2.0.0

### Stack Trace

Uncaught ReferenceError: callback is not defined

```
At /home/huba/.atom/packages/script-runner/lib/script-runner-process.coffee:72

ReferenceError: callback is not defined
    at ScriptRunnerProcess.module.exports.ScriptRunnerProcess.execute (/home/huba/.atom/packages/script-runner/lib/script-runner-process.coffee:72:5)
    at Function.module.exports.ScriptRunnerProcess.run (/home/huba/.atom/packages/script-runner/lib/script-runner-process.coffee:13:25)
    at /home/huba/code/script-runner/lib/script-runner.coffee:122:46
    at /home/huba/.atom/packages/script-runner/node_modules/shell-environment/lib/index.js:39:20
    at /home/huba/.atom/packages/script-runner/node_modules/shell-environment/lib/index.js:49:18
    at ChildProcess.<anonymous> (/home/huba/.atom/packages/script-runner/node_modules/shell-environment/lib/index.js:81:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by ioquatix** [comment]
@huba this should be relatively easy, if you have a moment do you think you could fix it?

**Comment by huba** [comment]
Sure I just put it up here to keep track of it.

**Comment by ioquatix** [comment]
Thanks for fixing this.
