### ISSUE TITLE
Cannot find module '..\build\Release\pty.node' Win10 atom

### ISSUE THREAD

**Issue by garretholland** [ioquatix/script-runner#71]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package 2.1.1

### Stack Trace

Failed to load the script-runner package

```
At Cannot find module '..\build\Release\pty.node'

Error: Cannot find module '..\build\Release\pty.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/script-runner/node_modules/node-pty/lib/windowsPtyAgent.js:4:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/script-runner/node_modules/node-pty/lib/windowsTerminal.js:8:25)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/script-runner/node_modules/node-pty/lib/index.js:5:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.8.60 
browser-plus 0.0.87 
highlight-selected 0.12.0 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.5.0 
monokai-seti 0.7.0 
script 3.14.1 
script-runner 2.1.1 
seti-ui 1.6.1 
```

**Comment by huba** [comment]
This is an issue with ptyjs on Windows, I'm not sure any of the core developers have the time or knowledge to fix this. Any help with providing Windows support is appreciated.

Feel free to make a PR.

**Comment by ioquatix** [comment]
We using https://github.com/Tyriar/node-pty now and it should work... perhaps bug with node-pty

**Comment by chrobiche** [comment]
Same issue on Mac Os.

**Comment by ioquatix** [comment]
I tried to fix this issue upstream, but so far haven't had any luck.

The following information should help: https://github.com/ioquatix/script-runner#node-gyp-failures
