### ISSUE TITLE
Cannot find module '../build/Release/pty.node'

### ISSUE THREAD

**Issue by jQrgen** [ioquatix/script-runner#72]
Currently on Ubuntu 16.04. I get the following error when opening atom.
```
Cannot find module '../build/Release/pty.node'
Hide Stack Trace
Error: Cannot find module '../build/Release/pty.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jorgen/.atom/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:17:11)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jorgen/.atom/packages/script-runner/node_modules/node-pty/lib/index.js:9:16)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jorgen/.atom/packages/script-runner/lib/script-runner-process.coffee:2:7)
    at Object.<anonymous> (/home/jorgen/.atom/packages/script-runner/lib/script-runner-process.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

**Comment by ioquatix** [comment]
It means the pty module failed to build for some reason. Can you find log files for that failure? or can you try `npm install node-pty`

**Comment by ioquatix** [comment]
I tried to fix this issue upstream (in node-gyp), but so far haven't had any luck.

The following information should help: https://github.com/ioquatix/script-runner#node-gyp-failures
