### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by SayeedG** [ioquatix/script-runner#73]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package 2.1.1

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At /Users/sayeedgulmahamad/.atom/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:127

Error: This socket has been ended by the other party
    at PipeSocket.writeAfterFIN [as write] (net.js:286:12)
    at /packages/script-runner/lib/script-runner-process.coffee:106:21
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/np/wyn6g4hj6js76j5rfmcykhk00000gn/T/AppTranslocation/02ED4F98-A93E-4553-A36A-64009710ED9A/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/np/wyn6g4hj6js76j5rfmcykhk00000gn/T/AppTranslocation/02ED4F98-A93E-4553-A36A-64009710ED9A/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Terminal.term.Terminal.handler (/packages/script-runner/lib/script-runner-view.coffee:91:18)
    at Terminal.EventEmitter.emit (/packages/script-runner/node_modules/xterm/lib/EventEmitter.js:45:16)
    at Terminal.handler (/packages/script-runner/node_modules/xterm/lib/xterm.js:2813:10)
    at Terminal.keyPress (/packages/script-runner/node_modules/xterm/lib/xterm.js:2498:10)
    at /packages/script-runner/node_modules/xterm/lib/xterm.js:399:14)
```

### Commands

```
     -1:42.4.0 editor:newline (input.hidden-input)
  3x -1:40.2.0 core:backspace (input.hidden-input)
  2x -1:38 editor:newline (input.hidden-input)
     -1:35.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:35.4.0 snippets:expand (input.hidden-input)
     -1:35.4.0 editor:indent (input.hidden-input)
  2x -1:33.3.0 core:backspace (input.hidden-input)
     -1:29.2.0 core:move-right (input.hidden-input)
     -1:25.4.0 script:run (input.hidden-input)
     -1:17.3.0 editor:newline (input.hidden-input)
     -1:14.5.0 script:run (input.hidden-input)
  2x -1:12 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:42.9.0 core:paste (input.hidden-input)
     -0:41.7.0 run:script (input.hidden-input)
     -0:36.5.0 script:run (input.hidden-input)
  2x -0:13.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-javac 1.9.4 
linter-ui-default 1.6.0 
script 3.15.0 
script-runner 2.1.1 
```

**Comment by ioquatix** [comment]
We need to know how to reproduce the issue.

**Comment by ioquatix** [comment]
In the latest release I've added an error handler so this shouldn't come up.

https://github.com/ioquatix/script-runner/commit/49fccdd9af7a6fe66628a83c91725987fb7130ce
