### ISSUE TITLE
Terminal.loadAddon is not a function

### ISSUE THREAD

**Issue by clousr** [ioquatix/script-runner#84]
After install, I get this error here:
Terminal.loadAddon is not a function

Stack Trace:

TypeError: Terminal.loadAddon is not a function
    at Object.<anonymous> (/Users/rclous/.atom/packages/script-runner/lib/script-runner-view.js:9:10)
    at Object.<anonymous> (/Users/rclous/.atom/packages/script-runner/lib/script-runner-view.js:180:42)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/rclous/.atom/packages/script-runner/lib/script-runner.js:4:26)
    at Object.<anonymous> (/Users/rclous/.atom/packages/script-runner/lib/script-runner.js:152:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:34

**Comment by ioquatix** [comment]
This should be fixed in v2.2.2 which was just released.
