### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by btihen** [ioquatix/script-runner#88]
Reproduce: do
1. ctrl-x
2. resize the window to the left (making it bigger)

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package 2.2.2

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /Users/btihen/.atom/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:213

Error: ioctl(2) failed.
    at UnixTerminal.resize (/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:213:13)
    at /packages/script-runner/lib/script-runner-process.js:164:14)
    at Terminal.EventEmitter.emit (/packages/script-runner/node_modules/xterm/lib/EventEmitter.js:49:20)
    at Terminal.resize (/packages/script-runner/node_modules/xterm/lib/xterm.js:1314:10)
    at Object.exports.fit (/packages/script-runner/node_modules/xterm/lib/addons/fit/fit.js:73:12)
    at Terminal.Xterm.fit (/packages/script-runner/node_modules/xterm/lib/addons/fit/fit.js:82:20)
    at ScriptRunnerView.outputResized (/packages/script-runner/lib/script-runner-view.js:151:24)
    at /packages/script-runner/lib/script-runner-view.js:45:55)
```

### Commands

```
  6x -7:00.1.0 core:backspace (input.hidden-input)
     -6:40.9.0 core:save (input.hidden-input)
     -6:25.8.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -6:12.7.0 core:save (input.hidden-input)
     -4:02.6.0 core:backspace (input.hidden-input)
     -3:13.7.0 run:file (input.hidden-input)
  3x -2:01.3.0 script-runner:run (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
elm-format 3.0.0 
git-plus 7.10.0 
language-elixir 0.22.0 
language-elm 1.5.0 
language-kotlin 0.5.0 
language-swift 0.5.0 
minimap 4.29.8 
open-recent 5.0.0 
script-runner 2.2.2 
split-diff 1.5.2 
todo-show 2.2.0 
```

**Comment by ioquatix** [comment]
This looks like a bug in node-pty - which we can update, we are currently on 2.x but the latest version is 3.x - with breaking changes, but it would be good to do this.

**Comment by btihen** [comment]
nicely done - problem fixed - I can no longer reproduce the problem.
Thanks.

**Comment by ioquatix** [comment]
yay!
