### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isWrapped' of undefined

### ISSUE THREAD

**Issue by tthomas2** [ioquatix/script-runner#94]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package 2.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isWrapped' of undefined

```
At /Users/thanawatthomas/.atom/packages/script-runner/node_modules/xterm/lib/Linkifier.js:111

TypeError: Cannot read property 'isWrapped' of undefined
    at Linkifier._linkifyRow (/packages/script-runner/node_modules/xterm/lib/Linkifier.js:111:71)
    at Linkifier._linkifyRows (/packages/script-runner/node_modules/xterm/lib/Linkifier.js:53:18)
    at /packages/script-runner/node_modules/xterm/lib/Linkifier.js:48:69
```

### Commands

```
 20x -1:58.9.0 core:backspace (input.hidden-input)
  2x -1:44.7.0 editor:newline (input.hidden-input)
     -1:38.3.0 core:backspace (input.hidden-input)
  7x -1:36.5.0 core:move-right (input.hidden-input)
  4x -1:34.7.0 core:backspace (input.hidden-input)
  5x -1:32.2.0 script:run (input.hidden-input)
  5x -1:27.7.0 core:backspace (input.hidden-input)
  3x -1:24.9.0 script:run (input.hidden-input)
     -1:19.7.0 core:backspace (input.hidden-input)
  6x -1:18.4.0 script:run (input.hidden-input)
     -1:15.9.0 script-runner:run (input.hidden-input)
  7x -1:05.6.0 core:backspace (input.hidden-input)
  2x -0:55.8.0 script:run (input.hidden-input)
  2x -0:52.1.0 core:move-right (input.hidden-input)
  2x -0:51.5.0 editor:newline (input.hidden-input)
  3x -0:28.4.0 script-runner:run (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
autocomplete-python 1.10.5 
emmet 2.4.3 
file-icons 2.1.21 
highlight-selected 0.13.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
platformio-ide-terminal 2.8.1 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
script-runner 2.3.0 
seti-ui 1.10.0 
```

**Comment by ioquatix** [comment]
Thanks, we will investigate.

**Comment by ioquatix** [comment]
Is it possible to know the version of xterm.js?

**Comment by ioquatix** [comment]
This has been fixed upstream.
